spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: "jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1"
    username: "user"
    password: "pass"

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
#    schema: schema-base.sql

#app:
#  datasource:
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    url: "jdbc:hsqldb:mem:appdb;DB_CLOSE_DELAY=-1"
#    username: "user"
#    password: "pass"
#    schema: schema-base.sql


import:
  file:
    dir: "import/anime.stackexchange.com"
    posts: "Posts.xml"
    comments: "Comments.xml"
    badges: "Badges.xml"
    postHistory: "PostHistory.xml"
    users: "Users.xml"
    votes: "Votes.xml"

export:
  file:
    csv: "target/export/persons.csv"
    txt: "target/export/persons.txt"
